"""
Module 7 prompt generation with balanced dimension ordering.

Implements the PRISM-B (Perception Response Instrument for Structured
Measurement — Brand) elicitation prompt builder.

Background: synthetic cohort experiments (Run 15b) found a primacy effect
in JSON-based PRISM-B elicitation (eta-sq=.217).  Dimensions listed first
receive ~15.4% weight; dimensions listed last receive ~8.0%.  This module
supports three ordering modes so researchers can apply counterbalancing.

Ordering modes:
  "canonical"   — fixed S-N-I-E-So-Ec-C-T order (default, backward-compatible)
  "latin_square" — cyclic Latin square; 8 orderings, each dimension appears
                   in every position exactly once across the 8-row cycle
  "random"      — random permutation per call; seed parameter for reproducibility

References:
  R15: Spectral Metamerism in AI-Mediated Brand Perception (Zharnikov 2026v)
       Zenodo DOI 10.5281/zenodo.19422427 — primacy effect finding
"""

from __future__ import annotations

import random
from typing import Literal

from spectral_branding.validators._math import DIMENSIONS

# ---------------------------------------------------------------------------
# Canonical dimension order (Semiotic, Narrative, Ideological, Experiential,
# Social, Economic, Cultural, Temporal)
# ---------------------------------------------------------------------------

CANONICAL_DIMENSIONS: list[str] = list(DIMENSIONS)  # defensive copy

# ---------------------------------------------------------------------------
# Latin-square orderings
# ---------------------------------------------------------------------------
# A cyclic Latin square is generated by rotating the canonical sequence by one
# position per row.  This guarantees:
#   - every dimension appears in every position exactly once across 8 rows
#   - no extra dependencies (pure Python, no scipy/numpy needed here)
#
# Row 0 is the canonical order (identity rotation); rows 1-7 are successive
# left-rotations.

_N = len(CANONICAL_DIMENSIONS)  # 8

LATIN_SQUARE: list[list[str]] = [
    CANONICAL_DIMENSIONS[i:] + CANONICAL_DIMENSIONS[:i] for i in range(_N)
]

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

DimensionOrder = Literal["canonical", "latin_square", "random"]


def get_dimension_order(
    mode: DimensionOrder = "canonical",
    *,
    latin_square_row: int | None = None,
    seed: int | None = None,
) -> list[str]:
    """Return a list of the 8 SBT dimensions in the requested order.

    Parameters
    ----------
    mode:
        One of ``"canonical"``, ``"latin_square"``, or ``"random"``.
    latin_square_row:
        For ``"latin_square"`` mode only.  If ``None``, cycles automatically
        using an internal counter (call ``reset_latin_square_counter()`` to
        restart from row 0).  Pass an explicit integer 0-7 to select a
        specific row without advancing the counter.
    seed:
        For ``"random"`` mode only.  Integer seed for reproducibility.  If
        ``None``, the result is non-deterministic.

    Returns
    -------
    list[str]
        A permutation of the 8 canonical dimension names.
    """
    if mode == "canonical":
        return list(CANONICAL_DIMENSIONS)

    if mode == "latin_square":
        if latin_square_row is not None:
            if not (0 <= latin_square_row < _N):
                raise ValueError(
                    f"latin_square_row must be 0-{_N - 1}, got {latin_square_row}"
                )
            return list(LATIN_SQUARE[latin_square_row])
        # Auto-advance the global cyclic counter
        row = _latin_square_counter["value"] % _N
        _latin_square_counter["value"] += 1
        return list(LATIN_SQUARE[row])

    if mode == "random":
        dims = list(CANONICAL_DIMENSIONS)
        rng = random.Random(seed)
        rng.shuffle(dims)
        return dims

    raise ValueError(
        f"dimension_order must be 'canonical', 'latin_square', or 'random'; got {mode!r}"
    )


# Internal counter for latin_square auto-advance (module-level dict so it is
# mutable without a global statement)
_latin_square_counter: dict[str, int] = {"value": 0}


def reset_latin_square_counter() -> None:
    """Reset the auto-advance Latin-square counter to row 0."""
    _latin_square_counter["value"] = 0


# ---------------------------------------------------------------------------
# Prompt builder
# ---------------------------------------------------------------------------

_PRISM_B_SYSTEM_PREAMBLE = """\
You are a brand perception analyst using Spectral Brand Theory (SBT).
Evaluate the following brand and return a JSON object with exactly these keys:\
"""

_PRISM_B_SYSTEM_POSTAMBLE = """\

For each dimension provide a score from 1 (minimal/absent) to 10 (dominant/defining).
Scores must reflect the brand's actual signal strength on that dimension, not generic
importance. Output valid JSON only — no markdown fences, no commentary."""

_DIMENSION_DESCRIPTIONS: dict[str, str] = {
    "semiotic": "Visual/auditory identity (logo, colors, packaging, spatial design)",
    "narrative": "Stories, myths, messaging (origin story, content marketing, PR)",
    "ideological": "Values, ethics, purpose (sustainability, social positions, certifications)",
    "experiential": "Product quality, service, UX (R&D, support, onboarding)",
    "social": "Community, status, belonging (events, ambassadors, referrals, tiers)",
    "economic": "Price, value, financial signals (pricing strategy, discounts, payment terms)",
    "cultural": "Aesthetic codes, taste, cultural resonance (collaborations, design, trend alignment)",
    "temporal": 'Heritage, longevity, evolution (archives, anniversaries, "since XXXX")',
}


def generate_prism_b_prompt(
    brand_name: str,
    dimension_order: DimensionOrder = "canonical",
    *,
    latin_square_row: int | None = None,
    seed: int | None = None,
    include_descriptions: bool = True,
) -> dict[str, str]:
    """Build a PRISM-B elicitation prompt for a single brand.

    Parameters
    ----------
    brand_name:
        The brand to evaluate (e.g. ``"Hermes"``).
    dimension_order:
        Ordering mode for the dimension keys in the JSON response template.
        ``"canonical"`` (default) is backward-compatible.
        ``"latin_square"`` cycles through 8 balanced orderings.
        ``"random"`` shuffles per call (use ``seed`` for reproducibility).
    latin_square_row:
        Explicit row selection for ``"latin_square"`` mode (0-7).
        If ``None``, the global auto-advance counter is used.
    seed:
        Integer seed for ``"random"`` mode reproducibility.
    include_descriptions:
        Whether to include per-dimension descriptions in the system prompt.
        Default ``True``.  Set ``False`` for minimal prompts.

    Returns
    -------
    dict with keys ``"system"`` and ``"user"``.
    """
    dims = get_dimension_order(
        mode=dimension_order,
        latin_square_row=latin_square_row,
        seed=seed,
    )

    # Build the JSON template block showing the expected key order
    json_keys = ",\n  ".join(f'"{d}": <1-10>' for d in dims)
    json_template = "{\n  " + json_keys + "\n}"

    # Build dimension description block (follows the requested order)
    if include_descriptions:
        desc_lines = "\n".join(
            f"  {i + 1}. {d.upper()}: {_DIMENSION_DESCRIPTIONS[d]}"
            for i, d in enumerate(dims)
        )
        dim_block = f"\nDimension definitions (in response key order):\n{desc_lines}\n"
    else:
        dim_block = ""

    system_prompt = (
        _PRISM_B_SYSTEM_PREAMBLE
        + f"\n{json_template}"
        + dim_block
        + _PRISM_B_SYSTEM_POSTAMBLE
    )

    user_prompt = f"Brand: {brand_name}"

    return {"system": system_prompt, "user": user_prompt}
